
# version: '3.3'
services:
    api:
        build:
          dockerfile: Dockerfile
          context: .
  
        volumes:
          - .:/usr/src/app
        container_name: api_say_nest
        depends_on: 
            - say_nest_db
        environment: 
            NODE_ENV: production
            PORT: 8002
        ports:
            # containar : local server
            - 5000:8002
            # debugging port
            - 9229:9229
        command: npm run start:dev 

    say_nest_db:
        image: postgres:10.4
        container_name: postgresql_say_nest
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'say_nest'
            PORT: 5432
        restart: always
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - "35000:5432"
        command: postgres -c listen_addresses='*'


volumes:
    postgres:
    pgadmin: