FROM node:16.14.2-alpine AS development

ARG NPM_PRIVATE_REGISTRY_URL
ARG NPM_PRIVATE_REGISTRY_TOKEN

WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

COPY . .
RUN npm run build

EXPOSE 5000

CMD [ "npm", "run", "start:dev" ]
