FROM node:16.14.2-alpine AS development

ARG NPM_PRIVATE_REGISTRY_URL
ARG NPM_PRIVATE_REGISTRY_TOKEN

WORKDIR /usr/src/app

COPY [ "package.json", "yarn.lock*", "./" ]
RUN yarn install --frozen-lockfile

COPY . .
RUN npm run build

EXPOSE 5000

CMD [ "yarn", "start:dev" ]