

version: "3.9"
services:
    api:
        build:
          dockerfile: Dockerfile.dev
          context: .
          # Only will build development stage from our dockerfile
          target: development
        # Mount our host Directory to the docker container
        # Mount (.) current directory to the docker container /usr/src/app
        # reflect file changes from host to container
        volumes:
          - .:/usr/src/app
        container_name: api_say_nest
        depends_on: 
            - say_nest_db
        environment: 
            # DATABASE_URL: postgres://postgres:postgres@say_nest_db:5432/say_nest
            NODE_ENV: development
            PORT: 8002
        ports:
            - 5000:8002
            # debugging port
            - 9229:9229
        command: npm run start:dev 

    say_nest_db:
        image: postgres:10.4
        container_name: postgresql_say_nest
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'nest'
            PORT: 5432
        restart: always
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
        command: postgres -c listen_addresses='*'


volumes:
    postgres:
    pgadmin: