
# version: '3.3'
services:
  # Traefik Reverse Proxy
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"  # Enable the Traefik dashboard (optional, for debugging)
      - "--entrypoints.http.address=:80"  # Listen on HTTP port
      - "--entrypoints.https.address=:443"  # Listen on HTTPS port
      - "--providers.docker"  # Enable Docker provider for Traefik to discover services
      - "--certificatesresolvers.le.acme.httpchallenge=true"  # Let's Encrypt HTTP challenge
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.le.acme.email=youremail@example.com"  # Replace with your email
      - "--certificatesresolvers.le.acme.storage=/acme.json"  # Store certificates
    ports:
      - "80:80"    # Expose HTTP port
      - "443:443"  # Expose HTTPS port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow Traefik to access Docker API
      - "./acme.json:/acme.json"  # Store the certificates (make sure this file exists)
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.${ENVIRONMENT} == true
    api:
        build:
          dockerfile: Dockerfile
          context: .
  
        volumes:
          - .:/usr/src/app
        container_name: api_say_nest
        depends_on: 
            - say_nest_db
        environment: 
            NODE_ENV: production
            PORT: 8002
        ports:
            # containar : local server
            - 5000:8002
            # debugging port
            - 9229:9229
        command: npm run start:dev 

    say_nest_db:
        image: postgres:10.4
        container_name: postgresql_say_nest
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'say_nest'
            PORT: 5432
        restart: always
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - "35000:5432"
        command: postgres -c listen_addresses='*'


volumes:
    postgres:
    pgadmin: